# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20171126_1244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': '问题解答', 'verbose_name_plural': '问题解答'},
        ),
        migrations.AlterModelOptions(
            name='answercomment',
            options={'verbose_name': '答案回复评论', 'verbose_name_plural': '答案回复评论'},
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '文章资讯', 'verbose_name_plural': '文章资讯'},
        ),
        migrations.AlterModelOptions(
            name='articlesource',
            options={'verbose_name': '文章来源', 'verbose_name_plural': '文章来源'},
        ),
        migrations.AlterModelOptions(
            name='bulletscreen',
            options={'verbose_name': '弹幕', 'verbose_name_plural': '弹幕'},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name': '收藏', 'verbose_name_plural': '收藏'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '通用的评论表', 'verbose_name_plural': '通用的评论表'},
        ),
        migrations.AlterModelOptions(
            name='coupon',
            options={'verbose_name': '优惠券生成规则', 'verbose_name_plural': '优惠券生成规则'},
        ),
        migrations.AlterModelOptions(
            name='couponrecord',
            options={'verbose_name': '优惠券发放、消费纪录', 'verbose_name_plural': '优惠券发放、消费纪录'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '课程', 'verbose_name_plural': '课程'},
        ),
        migrations.AlterModelOptions(
            name='coursechapter',
            options={'verbose_name': '课程章节', 'verbose_name_plural': '课程章节'},
        ),
        migrations.AlterModelOptions(
            name='coursedetail',
            options={'verbose_name': '课程详情页内容', 'verbose_name_plural': '课程详情页内容'},
        ),
        migrations.AlterModelOptions(
            name='courseoutline',
            options={'verbose_name': '课程大纲', 'verbose_name_plural': '课程大纲'},
        ),
        migrations.AlterModelOptions(
            name='coursereview',
            options={'verbose_name': '课程评价', 'verbose_name_plural': '课程评价'},
        ),
        migrations.AlterModelOptions(
            name='courseschedule',
            options={'verbose_name': '课程进度计划表', 'verbose_name_plural': '课程进度计划表'},
        ),
        migrations.AlterModelOptions(
            name='coursesection',
            options={'verbose_name': '课时目录', 'verbose_name_plural': '课时目录'},
        ),
        migrations.AlterModelOptions(
            name='degreecourse',
            options={'verbose_name': '学位课程', 'verbose_name_plural': '学位课程'},
        ),
        migrations.AlterModelOptions(
            name='degreecoursereview',
            options={'verbose_name': '学位课程评价', 'verbose_name_plural': '学位课程评价'},
        ),
        migrations.AlterModelOptions(
            name='degreeregistrationform',
            options={'verbose_name': '学位课程报名表', 'verbose_name_plural': '学位课程报名表'},
        ),
        migrations.AlterModelOptions(
            name='enrolledcourse',
            options={'verbose_name': '已报名课程', 'verbose_name_plural': '已报名课程'},
        ),
        migrations.AlterModelOptions(
            name='enrolleddegreecourse',
            options={'verbose_name': '已报名的学位课程', 'verbose_name_plural': '已报名的学位课程'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': '用户反馈表', 'verbose_name_plural': '用户反馈表'},
        ),
        migrations.AlterModelOptions(
            name='homework',
            options={'verbose_name': '家庭作业', 'verbose_name_plural': '家庭作业'},
        ),
        migrations.AlterModelOptions(
            name='homeworkrecord',
            options={'verbose_name': '学员作业记录及成绩', 'verbose_name_plural': '学员作业记录及成绩'},
        ),
        migrations.AlterModelOptions(
            name='mentorgroup',
            options={'verbose_name': '导师组', 'verbose_name_plural': '导师组'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': '消息通知纪录', 'verbose_name_plural': '消息通知纪录'},
        ),
        migrations.AlterModelOptions(
            name='oftenaskedquestion',
            options={'verbose_name': '常见问题', 'verbose_name_plural': '常见问题'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '订单', 'verbose_name_plural': '订单'},
        ),
        migrations.AlterModelOptions(
            name='orderdetail',
            options={'verbose_name': '订单详情', 'verbose_name_plural': '订单详情'},
        ),
        migrations.AlterModelOptions(
            name='pricepolicy',
            options={'verbose_name': '价格与有课程效期表', 'verbose_name_plural': '价格与有课程效期表'},
        ),
        migrations.AlterModelOptions(
            name='qacounter',
            options={'verbose_name': '问题和回答的赞同数量统计', 'verbose_name_plural': '问题和回答的赞同数量统计'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': '课程提问', 'verbose_name_plural': '课程提问'},
        ),
        migrations.AlterModelOptions(
            name='scholarship',
            options={'verbose_name': '学位课程奖学金', 'verbose_name_plural': '学位课程奖学金'},
        ),
        migrations.AlterModelOptions(
            name='scorerecord',
            options={'verbose_name': '积分奖惩记录', 'verbose_name_plural': '积分奖惩记录'},
        ),
        migrations.AlterModelOptions(
            name='scorerule',
            options={'verbose_name': '积分规则', 'verbose_name_plural': '积分规则'},
        ),
        migrations.AlterModelOptions(
            name='studyrecord',
            options={'verbose_name': '学位课程的模块学习进度', 'verbose_name_plural': '学位课程的模块学习进度'},
        ),
        migrations.AlterModelOptions(
            name='stufollowuprecord',
            options={'verbose_name': '学员跟进记录', 'verbose_name_plural': '学员跟进记录'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': '标签', 'verbose_name_plural': '标签'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': '讲师、导师表', 'verbose_name_plural': '讲师、导师表'},
        ),
        migrations.AlterModelOptions(
            name='transactionrecord',
            options={'verbose_name': '贝里交易纪录', 'verbose_name_plural': '贝里交易纪录'},
        ),
        migrations.RemoveField(
            model_name='coursedetail',
            name='recommend_courses',
        ),
        migrations.AddField(
            model_name='coursedetail',
            name='recommend_coursesy',
            field=models.ManyToManyField(blank=True, related_name='recommend_by', to='app01.Course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='pub_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='发布日期'),
        ),
    ]
